name: Node.js CI

on:
  push:
    branches:
      - main
      - main 1
      - master
  pull_request:
    branches:
      - main
      - main 1
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build
        run: npm run build
